### ISSUE TITLE
problems with the conversion to NetCDF

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/data-retrieval#9]
It seems that not all NetCDF variables are created correctly.
- There are only zero numbers in the variables TROPOPAUSE, TROPOPAUSE_PRESS, TROPOPAUSE_SECOND and TROPOPAUSE_SECOND_PRESSURE (sfc)
- the variables 10u 10v hcc lcc mcc msl z do not have an attribute "units" and no "standard_name"
- lnsp has no attribute "standard_name"

To me it is not clear, how much this affects the plots created by MSS. 
If this helps, here are some error messages like
[...]
ncrename: INFO Optional variable 'var129' not present in
mss/ecmwf_20211217_00.036.pv.nc, skipping it
Adding geopotential height...
[...]
Creating potential vorticity level file...
/home/ms/datex/df8/.local/lib/python3.8/site-packages/metpy/interpolate/one_dime
nsion.py:137: UserWarning: Interpolation point out of data bounds
encountered
   warnings.warn('Interpolation point out of data bounds encountered')

exact script in branch ecgate-forecast of fork jgrooss/data-retrieval.git
example data available from jgrooss

**Comment by joernu76** [comment]
Should be fixed with most recent merges.
